# Generated by Django 4.2.30 on 2026-07-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_permission_membershippermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membershippermission',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='membershippermission',
            constraint=models.UniqueConstraint(fields=('membership', 'permission'), name='unique_membership_permission'),
        ),
    ]
