# Generated by Django 4.2.30 on 2026-07-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_resolve_duplicate_memberships'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storemembership',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='storemembership',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_store_membership_user'),
        ),
    ]
