# Generated by Django 4.2.30 on 2026-08-03 12:37

from django.db import migrations, models

PERMISSION_CATALOG = (
    ("manage_catalog", "Manage Catalog"),
    ("view_inventory", "View Inventory"),
    ("manage_inventory", "Manage Inventory"),
    ("create_sale", "Create Sale"),
    ("view_sales", "View Sales"),
    ("manage_customers", "Manage Customers"),
    ("manage_wanted", "Manage Wanted"),
    ("view_dashboard", "View Dashboard"),
    ("manage_members", "Manage Members"),
)


def seed_permission_catalog(apps, schema_editor):
    Permission = apps.get_model("stores", "Permission")

    for code, name in PERMISSION_CATALOG:
        Permission.objects.update_or_create(
            code=code,
            defaults={"name": name},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_enforce_one_membership_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RunPython(
            seed_permission_catalog,
            migrations.RunPython.noop,
        ),
    ]
