# Generated by Django 5.2.17 on 2026-09-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_invitation_and_default_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='notification_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
