# Generated by Django 4.2.30 on 2026-07-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_category_options'),
        ('customers', '0001_initial'),
        ('stores', '0003_alter_membershippermission_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(max_length=20)),
                ('wanted_count', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wanted_products', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_products', to='stores.store')),
            ],
            options={
                'verbose_name_plural': 'Wanted',
                'unique_together': {('store', 'product_name', 'size')},
            },
        ),
        migrations.CreateModel(
            name='WantedCustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('wanted_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_requests', to='wanted.wantedproduct')),
            ],
        ),
    ]
