# Generated by Django 4.2.30 on 2026-07-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='finl_price',
            new_name='final_price',
        ),
    ]
