# Generated by Django 4.2.30 on 2026-07-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_finl_price_saleitem_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'درحال تکمیل'), ('completed', 'تکمیل شده'), ('cancelled', 'کنسل شده')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
