# Generated by Django 4.2.30 on 2026-07-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_status_alter_sale_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='chanel',
            new_name='channel',
        ),
    ]
