# Generated by Django 5.2.17 on 2026-09-20 07:57

from django.db.models import F
from django.db import migrations, models


def backfill_completed_at(apps, schema_editor):
    Sale = apps.get_model('sales', 'Sale')

    Sale.objects.filter(
        status__in=['completed', 'cancelled'],
        completed_at__isnull=True,
    ).update(
        completed_at=F('created_at'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_saleitem_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_completed_at,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(
                fields=['store', 'status', 'completed_at'],
                name='sale_store_status_done_at_idx',
            ),
        ),
    ]
